import 'package:flutter/material.dart';
import '../models/service_model.dart';
import '../models/dependency_model.dart';

final List<ServiceModel> seedServices = [
  const ServiceModel(
    id: 'svc-power',
    name: 'Power Grid',
    slug: 'power-grid',
    category: 'Energy',
    criticality: 5,
    state: 'HEALTHY',
    description: 'Primary electrical distribution for the city core.',
    position: Offset(320, 20),
    recoveryDuration: 6,
  ),
  const ServiceModel(
    id: 'svc-hospital',
    name: 'Hospital',
    slug: 'hospital',
    category: 'Healthcare',
    criticality: 5,
    state: 'HEALTHY',
    description: 'Regional hospital providing critical care services.',
    position: Offset(80, 180),
    recoveryDuration: 6,
  ),
  const ServiceModel(
    id: 'svc-water',
    name: 'Water Supply',
    slug: 'water-supply',
    category: 'Water',
    criticality: 4,
    state: 'HEALTHY',
    description: 'Municipal water treatment and distribution network.',
    position: Offset(280, 180),
    recoveryDuration: 5,
  ),
  const ServiceModel(
    id: 'svc-transport',
    name: 'Public Transport',
    slug: 'public-transport',
    category: 'Transport',
    criticality: 4,
    state: 'HEALTHY',
    description: 'Bus and rail transit connecting districts.',
    position: Offset(480, 180),
    recoveryDuration: 5,
  ),
  const ServiceModel(
    id: 'svc-communication',
    name: 'Communication Network',
    slug: 'communication-network',
    category: 'Communication',
    criticality: 4,
    state: 'HEALTHY',
    description: 'City-wide telecom and emergency communications backbone.',
    position: Offset(680, 180),
    recoveryDuration: 5,
  ),
  const ServiceModel(
    id: 'svc-emergency',
    name: 'Emergency Services',
    slug: 'emergency-services',
    category: 'Emergency',
    criticality: 5,
    state: 'HEALTHY',
    description: 'Fire, police, and medical emergency response coordination.',
    position: Offset(320, 360),
    recoveryDuration: 6,
  ),
  const ServiceModel(
    id: 'svc-residential',
    name: 'Residential Areas',
    slug: 'residential-areas',
    category: 'Residential',
    criticality: 3,
    state: 'HEALTHY',
    description: 'Dense residential districts dependent on utility services.',
    position: Offset(280, 520),
    recoveryDuration: 4,
  ),
  const ServiceModel(
    id: 'svc-waste',
    name: 'Waste Management',
    slug: 'waste-management',
    category: 'Waste',
    criticality: 2,
    state: 'HEALTHY',
    description: 'Sanitation and waste collection operations.',
    position: Offset(680, 360),
    recoveryDuration: 4,
  ),
];

final List<DependencyModel> seedDependencies = [
  const DependencyModel(
    id: 'dep-power-hospital',
    sourceServiceId: 'svc-power',
    targetServiceId: 'svc-hospital',
    dependencyStrength: 1.0,
  ),
  const DependencyModel(
    id: 'dep-power-water',
    sourceServiceId: 'svc-power',
    targetServiceId: 'svc-water',
    dependencyStrength: 1.0,
  ),
  const DependencyModel(
    id: 'dep-power-transport',
    sourceServiceId: 'svc-power',
    targetServiceId: 'svc-transport',
    dependencyStrength: 1.0,
  ),
  const DependencyModel(
    id: 'dep-power-communication',
    sourceServiceId: 'svc-power',
    targetServiceId: 'svc-communication',
    dependencyStrength: 1.0,
  ),
  const DependencyModel(
    id: 'dep-hospital-emergency',
    sourceServiceId: 'svc-hospital',
    targetServiceId: 'svc-emergency',
    dependencyStrength: 1.0,
  ),
  const DependencyModel(
    id: 'dep-transport-emergency',
    sourceServiceId: 'svc-transport',
    targetServiceId: 'svc-emergency',
    dependencyStrength: 0.9,
  ),
  const DependencyModel(
    id: 'dep-water-residential',
    sourceServiceId: 'svc-water',
    targetServiceId: 'svc-residential',
    dependencyStrength: 1.0,
  ),
  const DependencyModel(
    id: 'dep-power-waste',
    sourceServiceId: 'svc-power',
    targetServiceId: 'svc-waste',
    dependencyStrength: 0.7,
  ),
];
